name: Publicar mi Web de Documentación # Nombre del robot
on:
push:
branches: [ main ] # El robot se activa cuando guardas en la rama 'main'
jobs:
construir-y-publicar:
runs-on: ubuntu-latest # Usa una computadora con Linux
steps:
- name: Descargar mi código
uses: actions/checkout@v3 # El robot baja tu código para leerlo
- name: Instalar herramientas
run: npm install # El robot instala lo que necesita
- name: Crear la web
run: npm run build # El robot transforma Markdown a HTML
